### add
POST {{url}}/cart/add
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": 9999999,
  "cartEntries": [
    {
      "id": 3,
      "amount": 1
    }
  ]
}


### list
GET {{url}}/cart/list
Authorization: Bearer {{token}}

### checkout
GET {{url}}/cart/checkout
Authorization: Bearer {{token}}