### create
POST {{url}}/category/create
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Erwachsene",
  "price": 25.5,
  "stock": 100,
  "eventId": 1
}

### update
PUT {{url}}/category/update
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": 1,
  "name": "Erwachsene",
  "price": 25.5,
  "stock": 100
}

### delete
DELETE {{url}}/category/delete/1
Authorization: Bearer {{token}}

### list
GET {{url}}/category/list
Authorization: Bearer {{token}}

### load
GET {{url}}/category/2
Authorization: Bearer {{token}}
