### signup
POST {{url}}/user/signup
Content-Type: application/json

{
  "email": "ratp@htl-steyr.ac.at",
  "password": "test",
  "firstname": "Peter",
  "lastname": "Rathgeb"
}

### signin
POST {{url}}/user/signin
Content-Type: application/json

{
  "email": "admin@email.com",
  "password": "a"
}


### update
PUT {{url}}/user/update
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "email": "ratp@htl-steyr.ac.at",
  "firstname": "Peter Chef",
  "lastname": "Rathgeb"
}

### delete
DELETE {{url}}/user/delete/1
Authorization: Bearer {{token}}

### list
GET {{url}}/user/list
Authorization: Bearer {{token}}

### load
GET {{url}}/user/load/2
Authorization: Bearer {{token}}
